# Generated by Django 5.2.12 on 2026-03-25 19:53

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WdmCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(db_index=True, default='planned', max_length=50)),
                ('wavelength_nm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wdm_circuits', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'WDM circuit',
                'verbose_name_plural': 'WDM circuits',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WdmNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('node_type', models.CharField(max_length=50)),
                ('grid', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wdm_node', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'WDM node',
                'verbose_name_plural': 'WDM nodes',
                'ordering': ('device',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WdmChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('grid_position', models.PositiveIntegerField()),
                ('wavelength_nm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('label', models.CharField(max_length=20)),
                ('status', models.CharField(db_index=True, default='available', max_length=50)),
                ('demux_front_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.frontport')),
                ('mux_front_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.frontport')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('wdm_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='netbox_wdm.wdmnode')),
            ],
            options={
                'verbose_name': 'WDM channel',
                'verbose_name_plural': 'WDM channels',
                'ordering': ('wdm_node', 'grid_position'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WdmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('node_type', models.CharField(max_length=50)),
                ('grid', models.CharField(max_length=50)),
                ('fiber_type', models.CharField(default='duplex', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wdm_profile', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'WDM profile',
                'verbose_name_plural': 'WDM profiles',
                'ordering': ('device_type',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WdmChannelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('grid_position', models.PositiveIntegerField()),
                ('wavelength_nm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('label', models.CharField(max_length=20)),
                ('demux_front_port_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.frontporttemplate')),
                ('mux_front_port_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.frontporttemplate')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_plans', to='netbox_wdm.wdmprofile')),
            ],
            options={
                'verbose_name': 'WDM channel plan',
                'verbose_name_plural': 'WDM channel plans',
                'ordering': ('profile', 'grid_position'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WdmCircuitPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_wdm.wdmchannel')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_segments', to='netbox_wdm.wdmcircuit')),
            ],
            options={
                'verbose_name': 'WDM circuit path',
                'verbose_name_plural': 'WDM circuit paths',
                'ordering': ('circuit', 'sequence'),
                'constraints': [models.UniqueConstraint(fields=('circuit', 'channel'), name='unique_circuit_channel'), models.UniqueConstraint(fields=('circuit', 'sequence'), name='unique_circuit_sequence')],
            },
        ),
        migrations.CreateModel(
            name='WdmLinePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('direction', models.CharField(max_length=50)),
                ('role', models.CharField(default='bidi', max_length=50)),
                ('rear_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.rearport')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('wdm_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ports', to='netbox_wdm.wdmnode')),
            ],
            options={
                'verbose_name': 'WDM line port',
                'verbose_name_plural': 'WDM line ports',
                'ordering': ('wdm_node', 'direction', 'role'),
                'constraints': [models.UniqueConstraint(fields=('wdm_node', 'rear_port'), name='unique_lineport_rear_port'), models.UniqueConstraint(fields=('wdm_node', 'direction', 'role'), name='unique_lineport_direction_role')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='wdmchannel',
            constraint=models.UniqueConstraint(fields=('wdm_node', 'wavelength_nm'), name='unique_channel_wavelength'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannel',
            constraint=models.UniqueConstraint(fields=('wdm_node', 'grid_position'), name='unique_channel_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('mux_front_port__isnull', False)), fields=('wdm_node', 'mux_front_port'), name='unique_node_mux_fp'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('demux_front_port__isnull', False)), fields=('wdm_node', 'demux_front_port'), name='unique_node_demux_fp'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannelplan',
            constraint=models.UniqueConstraint(fields=('profile', 'wavelength_nm'), name='unique_profile_wavelength'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannelplan',
            constraint=models.UniqueConstraint(fields=('profile', 'grid_position'), name='unique_profile_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannelplan',
            constraint=models.UniqueConstraint(condition=models.Q(('mux_front_port_template__isnull', False)), fields=('profile', 'mux_front_port_template'), name='unique_profile_fpt'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannelplan',
            constraint=models.UniqueConstraint(condition=models.Q(('demux_front_port_template__isnull', False)), fields=('profile', 'demux_front_port_template'), name='unique_profile_demux_fpt'),
        ),
    ]
