# Generated by Django 5.2.12 on 2026-03-27 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_wdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WdmWavelengthPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('grid_position', models.PositiveIntegerField()),
                ('wavelength_nm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'WDM wavelength path',
                'verbose_name_plural': 'WDM wavelength paths',
                'ordering': ('wavelength_nm',),
            },
        ),
        migrations.CreateModel(
            name='WdmWavelengthPathChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wavelength_path_entries', to='netbox_wdm.wdmchannel')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_channels', to='netbox_wdm.wdmwavelengthpath')),
            ],
            options={
                'verbose_name': 'wavelength path channel',
                'verbose_name_plural': 'wavelength path channels',
                'ordering': ('path', 'sequence'),
                'constraints': [models.UniqueConstraint(fields=('path', 'channel'), name='unique_wavelength_path_channel'), models.UniqueConstraint(fields=('path', 'sequence'), name='unique_wavelength_path_sequence')],
            },
        ),
    ]
