# Generated by Django 5.2.12 on 2026-03-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        ('netbox_wdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wavelengthchannel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wavelengthservicechannelassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wdmchanneltemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wdmtrunkport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wavelengthchannel',
            name='front_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.frontport'),
        ),
        migrations.AlterField(
            model_name='wavelengthchannel',
            name='status',
            field=models.CharField(db_index=True, default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='wavelengthservice',
            name='status',
            field=models.CharField(db_index=True, default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='wdmchanneltemplate',
            name='front_port_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.frontporttemplate'),
        ),
        migrations.AlterField(
            model_name='wdmtrunkport',
            name='rear_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.rearport'),
        ),
        migrations.AddConstraint(
            model_name='wavelengthchannel',
            constraint=models.UniqueConstraint(fields=('wdm_node', 'wavelength_nm'), name='unique_channel_wavelength'),
        ),
        migrations.AddConstraint(
            model_name='wavelengthchannel',
            constraint=models.UniqueConstraint(fields=('wdm_node', 'grid_position'), name='unique_channel_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='wavelengthservicechannelassignment',
            constraint=models.UniqueConstraint(fields=('service', 'channel'), name='unique_wsca_service_channel'),
        ),
        migrations.AddConstraint(
            model_name='wavelengthservicechannelassignment',
            constraint=models.UniqueConstraint(fields=('service', 'sequence'), name='unique_wsca_service_sequence'),
        ),
        migrations.AddConstraint(
            model_name='wdmchanneltemplate',
            constraint=models.UniqueConstraint(fields=('profile', 'wavelength_nm'), name='unique_profile_wavelength'),
        ),
        migrations.AddConstraint(
            model_name='wdmchanneltemplate',
            constraint=models.UniqueConstraint(fields=('profile', 'grid_position'), name='unique_profile_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='wdmtrunkport',
            constraint=models.UniqueConstraint(fields=('wdm_node', 'rear_port'), name='unique_trunkport_rear_port'),
        ),
        migrations.AddConstraint(
            model_name='wdmtrunkport',
            constraint=models.UniqueConstraint(fields=('wdm_node', 'direction'), name='unique_trunkport_direction'),
        ),
    ]
