# Generated by Django 5.2.12 on 2026-03-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_wdm', '0002_wdmwavelengthpath_wdmwavelengthpathchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdmcircuit',
            name='wavelength_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits', to='netbox_wdm.wdmwavelengthpath'),
        ),
        migrations.RemoveField(
            model_name='wdmcircuit',
            name='wavelength_nm',
        ),
        migrations.DeleteModel(
            name='WdmCircuitPath',
        ),
    ]
