# Generated by Django 5.2.12 on 2026-03-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_wdm', '0003_remove_wdmcircuit_wavelength_nm_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wdmchannel',
            name='unique_channel_wavelength',
        ),
        migrations.RemoveField(
            model_name='wdmchannel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='wdmchannel',
            name='wavelength_nm',
        ),
    ]
