# Generated by Django 5.2.12 on 2026-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_wdm', '0005_wdmwavelengthpath_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdmwavelengthpath',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
