# Generated by Django 5.2.12 on 2026-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_wdm', '0006_wdmwavelengthpath_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdmnode',
            name='expected_port_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wdmnode',
            name='port_sync_valid',
            field=models.BooleanField(default=True),
        ),
    ]
