# Generated by Django 5.2.12 on 2026-03-31 02:21

from django.db import migrations, models


def copy_fk_to_m2m(apps, schema_editor):
    """Copy existing wavelength_path FK values into the new M2M relationship."""
    WdmCircuit = apps.get_model("netbox_wdm", "WdmCircuit")
    for circuit in WdmCircuit.objects.filter(wavelength_path__isnull=False):
        circuit.wavelength_paths.add(circuit.wavelength_path)


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_wdm", "0007_wdmnode_expected_port_hash_wdmnode_port_sync_valid"),
    ]

    operations = [
        # 1. Add the new M2M field
        migrations.AddField(
            model_name="wdmcircuit",
            name="wavelength_paths",
            field=models.ManyToManyField(
                blank=True,
                related_name="circuits",
                to="netbox_wdm.wdmwavelengthpath",
            ),
        ),
        # 2. Copy existing FK data to M2M
        migrations.RunPython(copy_fk_to_m2m, migrations.RunPython.noop),
        # 3. Remove the old FK field
        migrations.RemoveField(
            model_name="wdmcircuit",
            name="wavelength_path",
        ),
    ]
