# Generated by Django 5.2.16 on 2026-08-17 20:07

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0131_squashed_0159'),
        ('netbox_wdm', '0008_remove_wdmcircuit_wavelength_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WdmLinePortPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('direction', models.CharField(max_length=50)),
                ('role', models.CharField(default='bidi', max_length=50)),
            ],
            options={
                'verbose_name': 'WDM line port plan',
                'verbose_name_plural': 'WDM line port plans',
                'ordering': ('profile', 'direction', 'role'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='wdmprofile',
            options={'ordering': ('device_type', 'module_type')},
        ),
        migrations.RemoveConstraint(
            model_name='wdmchannel',
            name='unique_channel_grid_position',
        ),
        migrations.RemoveConstraint(
            model_name='wdmlineport',
            name='unique_lineport_direction_role',
        ),
        migrations.AddField(
            model_name='wdmchannel',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdm_channels', to='dcim.module'),
        ),
        migrations.AddField(
            model_name='wdmlineport',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdm_line_ports', to='dcim.module'),
        ),
        migrations.AddField(
            model_name='wdmprofile',
            name='module_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdm_profile', to='dcim.moduletype'),
        ),
        migrations.AlterField(
            model_name='wdmnode',
            name='grid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wdmnode',
            name='node_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wdmprofile',
            name='device_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdm_profile', to='dcim.devicetype'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', True)), fields=('wdm_node', 'grid_position'), name='unique_channel_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='wdmchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('wdm_node', 'module', 'grid_position'), name='unique_channel_module_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='wdmlineport',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', True)), fields=('wdm_node', 'direction', 'role'), name='unique_lineport_direction_role'),
        ),
        migrations.AddConstraint(
            model_name='wdmlineport',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('wdm_node', 'module', 'direction', 'role'), name='unique_lineport_module_direction_role'),
        ),
        migrations.AddConstraint(
            model_name='wdmprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device_type__isnull', False), ('module_type__isnull', True)), models.Q(('device_type__isnull', True), ('module_type__isnull', False)), _connector='OR'), name='wdmprofile_exactly_one_anchor'),
        ),
        migrations.AddField(
            model_name='wdmlineportplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_port_plans', to='netbox_wdm.wdmprofile'),
        ),
        migrations.AddField(
            model_name='wdmlineportplan',
            name='rear_port_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rearporttemplate'),
        ),
        migrations.AddField(
            model_name='wdmlineportplan',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddConstraint(
            model_name='wdmlineportplan',
            constraint=models.UniqueConstraint(fields=('profile', 'rear_port_template'), name='unique_lineportplan_rear_port_template'),
        ),
        migrations.AddConstraint(
            model_name='wdmlineportplan',
            constraint=models.UniqueConstraint(fields=('profile', 'direction', 'role'), name='unique_lineportplan_direction_role'),
        ),
    ]
