# Generated by Django 5.2.16 on 2026-08-18 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0131_squashed_0159'),
        ('netbox_wdm', '0009_module_scoped_overlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdmlineport',
            name='rear_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rearport'),
        ),
    ]
