# Generated by Django 5.2.16 on 2026-08-18 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_wdm', '0010_alter_wdmlineport_rear_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdmwavelengthpathchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wavelength_path_entries', to='netbox_wdm.wdmchannel'),
        ),
    ]
